// (error, current_line, ch)
pub const TokenizerErrorProc = *const fn (TokenizerError, usize, u21) void;

pub const TokenizerError = enum {
    SurrogateInInputStream,
    NoncharacterInInputStream,
    ControlCharacterInInputStream,
    UnexpectedNullCharacter,
    EofBeforeTagName,
    UnexpectedQuestionMarkInsteadOfTagName,
    InvalidFirstCharacterOfTagName,
    MissingEndTagName,
    EofInTag,
    EofInScriptHtmlCommentLikeText,
    UnexpectedEqualsSignBeforeAttributeName,
    UnexpectedCharacterInAttributeName,
    MissingAttributeValue,
    MissingWhitespaceBetweenAttributes,
    UnexpectedSolidusInTag,
    DuplicateAttribute,
    UnexpectedCharacterInUnquotedAttributeValue,
    IncorrectlyOpenedComment,
    IncorrectlyClosedComment,
    AbruptClosingOfEmptyComment,
    EofInComment,
    NestedComment,
    EofInDOCTYPE,
    MissingWhitespaceBeforeDOCTYPEName,
    MissingDOCTYPEName,
    InvalidCharacterSequenceAfterDOCTYPEName,
    MissingWhitespaceAfterDOCTYPEPublicKeyword,
    MissingDOCTYPEPublicIdentifier,
    MissingQuoteBeforeDOCTYPEPublicIdentifier,
    AbruptDOCTYPEPublicIdentifier,
    MissingWhitespaceBetweenDOCTYPEPublicAndSystemIdentifiers,
    MissingQuoteBeforeDOCTYPESystemIdentifier,
    MissingWhitespaceAfterDOCTYPESystemKeyword,
    MissingDOCTYPESystemIdentifier,
    AbruptDOCTYPESystemIdentifier,
    UnexpectedCharacterAfterDOCTYPESystemIdentifier,
    CDATAInHtmlContent,
    EofInCDATA,
    MissingSemicolonAfterCharacterReference,
    AbsenceOfDigitsInNumericCharacterReference,
    NullCharacterReference,
    CharacterReferenceOutsideUnicodeRange,
    SurrogateCharacterReference,
    NoncharacterCharacterReference,
    ControlCharacterReference,
    UnknownNamedCharacterReference,
    CreateElementForToken,
    InvaildProcessingInstructionTarget,
    InvalidFirstCharacterOfProcessingInstructionTarget,
    DisallowedProcessingInstructionTarget,
    EofInProcessingInstruction,
    EndTagWithAttributes,
    EndTagWithSelfClosing,
};

pub fn tokenizerErrorToString(self: TokenizerError) []const u8 {
    return switch (self) {
        .SurrogateInInputStream => "surrogate-in-input-stream",
        .NoncharacterInInputStream => "noncharacter-in-input-stream",
        .ControlCharacterInInputStream => "control-character-in-input-stream",
        .UnexpectedNullCharacter => "unexpected-null-character",
        .EofBeforeTagName => "eof-before-tag-name",
        .UnexpectedQuestionMarkInsteadOfTagName => "unexpected-question-mark-instead-of-tag-name",
        .InvalidFirstCharacterOfTagName => "invalid-first-character-of-tag-name",
        .MissingEndTagName => "missing-end-tag-name",
        .EofInTag => "eof-in-tag",
        .EofInScriptHtmlCommentLikeText => "eof-in-script-html-comment-like-text",
        .UnexpectedEqualsSignBeforeAttributeName => "unexpected-equals-sign-before-attribute-name",
        .UnexpectedCharacterInAttributeName => "unexpected-character-in-attribute-name",
        .MissingAttributeValue => "missing-attribute-value",
        .MissingWhitespaceBetweenAttributes => "missing-whitespace-between-attributes",
        .UnexpectedSolidusInTag => "unexpected-solidus-in-tag",
        .DuplicateAttribute => "duplicate-attribute",
        .UnexpectedCharacterInUnquotedAttributeValue => "unexpected-character-in-unquoted-attribute-value",
        .IncorrectlyOpenedComment => "incorrectly-opened-comment",
        .IncorrectlyClosedComment => "incorrectly-closed-comment",
        .AbruptClosingOfEmptyComment => "abrupt-closing-of-empty-comment",
        .EofInComment => "eof-in-comment",
        .NestedComment => "nested-comment",
        .EofInDOCTYPE => "eof-in-doctype",
        .MissingWhitespaceBeforeDOCTYPEName => "missing-whitespace-before-doctype-name",
        .MissingDOCTYPEName => "missing-doctype-name",
        .InvalidCharacterSequenceAfterDOCTYPEName => "invalid-character-sequence-after-doctype-name",
        .MissingWhitespaceAfterDOCTYPEPublicKeyword => "missing-whitespace-after-doctype-public-keyword",
        .MissingDOCTYPEPublicIdentifier => "missing-doctype-public-identifier",
        .MissingQuoteBeforeDOCTYPEPublicIdentifier => "missing-quote-before-doctype-public-identifier",
        .AbruptDOCTYPEPublicIdentifier => "abrupt-doctype-public-identifier",
        .MissingWhitespaceBetweenDOCTYPEPublicAndSystemIdentifiers => "missing-whitespace-between-doctype-public-and-system-identifiers",
        .MissingQuoteBeforeDOCTYPESystemIdentifier => "missing-quote-before-doctype-system-identifier",
        .MissingWhitespaceAfterDOCTYPESystemKeyword => "missing-whitespace-after-doctype-system-keyword",
        .MissingDOCTYPESystemIdentifier => "missing-doctype-system-identifier",
        .AbruptDOCTYPESystemIdentifier => "abrupt-doctype-system-identifier",
        .UnexpectedCharacterAfterDOCTYPESystemIdentifier => "unexpected-character-after-doctype-system-identifier",
        .CDATAInHtmlContent => "cdata-in-html-content",
        .EofInCDATA => "eof-in-cdata",
        .MissingSemicolonAfterCharacterReference => "missing-semicolon-after-character-reference",
        .AbsenceOfDigitsInNumericCharacterReference => "absence-of-digits-in-numeric-character-reference",
        .NullCharacterReference => "null-character-reference",
        .CharacterReferenceOutsideUnicodeRange => "character-reference-outside-unicode-range",
        .SurrogateCharacterReference => "surrogate-character-reference",
        .NoncharacterCharacterReference => "noncharacter-character-reference",
        .ControlCharacterReference => "control-character-reference",
        .UnknownNamedCharacterReference => "unknown-named-character-reference",
        .CreateElementForToken => "create-element-for-token",
        .InvaildProcessingInstructionTarget => "invaild-processing-instruction-target",
        .InvalidFirstCharacterOfProcessingInstructionTarget => "invalid-first-character-of-processing-instruction-target",
        .DisallowedProcessingInstructionTarget => "disallowed-processing-instruction-target",
        .EofInProcessingInstruction => "eof-in-processing-instruction",
        .EndTagWithAttributes => "end-tag-with-attributes",
        .EndTagWithSelfClosing => "end-tag-with-trailing-solidus",
    };
}

