import os
import json

input_path = "res/json/named_char_refs.json"
output_dir = "src/renderer/html/tokenizer"
output_file = "named_char_refs_gen.zig"
output_path = os.path.join(output_dir, output_file)

os.makedirs(output_dir, exist_ok=True)

with open(input_path, "r", encoding="utf-8") as f:
    data = json.load(f)

with open(output_path, "w", encoding="utf-8") as f:
    f.write("// Code generated by script. DO NOT EDIT.\n")
    f.write(
        "// Source: https://html.spec.whatwg.org/multipage/named-characters.html\n\n"
    )

    f.write('const std = @import("std");\n\n')

    f.write(
        "pub const named_char_refs = std.StaticStringMap([]const u8).initComptime(.{\n"
    )

    for k, v in data.items():
        key = k[1:] if k.startswith("&") else k

        value = (
            v["characters"]
            .replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
        )

        f.write(f'    .{{ "{key}", "{value}" }},\n')

    f.write("});\n")

print(f"Success: Generated {len(data)} entries -> {output_path}")
