import os
import json

input_path = "res/json/named_char_refs.json"
output_dir = "src/renderer/html/tokenizer"
output_file = "named_char_refs_gen.zig"
output_path = os.path.join(output_dir, output_file)

os.makedirs(output_dir, exist_ok=True)

with open(input_path, "r", encoding="utf-8") as f:
    data = json.load(f)

class TempTrieNode:
    def __init__(self, char):
        self.char = char
        self.value = None
        self.children = {}  # key: char, value: TempTrieNode
        self.child_start = 0
        self.child_count = 0

root = TempTrieNode('\0')

for k, v in data.items():
    key = k[1:] if k.startswith("&") else k
    val_str = v["characters"]
    
    current = root
    for char in key:
        if char not in current.children:
            current.children[char] = TempTrieNode(char)
        current = current.children[char]
    current.value = val_str

flat_nodes = [root]
idx = 0
while idx < len(flat_nodes):
    curr_node = flat_nodes[idx]
    if curr_node.children:
        curr_node.child_start = len(flat_nodes)
        curr_node.child_count = len(curr_node.children)
        
        for c in sorted(curr_node.children.keys()):
            flat_nodes.append(curr_node.children[c])
    else:
        curr_node.child_start = 0
        curr_node.child_count = 0
    idx += 1

with open(output_path, "w", encoding="utf-8") as f:
    f.write(f"// Code generated by script: {os.path.basename(__file__)}. DO NOT EDIT.\n")
    f.write("// Source: https://html.spec.whatwg.org/multipage/named-characters.html\n\n")
    f.write('const std = @import("std");\n\n')
    
    f.write(
        "pub const TrieNode = struct {\n"
        "    char: u8,\n"
        "    child_start: u16,\n"
        "    child_count: u8,\n"
        "    value: ?[]const u8,\n"
        "};\n\n"
    )
    
    f.write(f"pub const trie_nodes = [{len(flat_nodes)}]TrieNode{{\n")
    
    for i, node in enumerate(flat_nodes):
        if node.char == '\0':
            char_repr = "0"
        elif node.char == "'":
            char_repr = "'\\''"
        elif node.char == "\\":
            char_repr = "'\\\\'"
        else:
            char_repr = f"'{node.char}'"
            
        if node.value is not None:
            escaped_val = (
                node.value
                .replace("\\", "\\\\")
                .replace('"', '\\"')
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t")
            )
            val_repr = f'"{escaped_val}"'
        else:
            val_repr = "null"
            
        f.write(
            f"    .{{ "
            f".char = {char_repr}, "
            f".child_start = {node.child_start}, "
            f".child_count = {node.child_count}, "
            f".value = {val_repr} "
            f"}}, // idx: {i}\n"
        )
        
    f.write("};\n")

print(f"Success: Built Trie with {len(flat_nodes)} nodes from {len(data)} entities.")
print(f"Generated -> {output_path}")
